### PR TITLE
Write new element in recent file

### PR DESCRIPTION
**Pull request by francesco-gaglione**

### CODE REVIEW

**Comment by francesco-gaglione** [comment]
The pull request can be considered over, but ... an investigation must be opened. If you use another file manager (nautilus for example) it goes and overwrites the entire recent files file thus losing the recent cosmic-file files (once implemented). so it is to be understood if it is a wrong behavior that nautilus is doing or if we are not respecting the freedesktop standard

**Comment by mmstick** [comment]
The written file is missing a lot of data. Make sure that it matches the original format.

**Comment by francesco-gaglione** [comment]
Now should match original data format, some improvement should be done and some changes to be compliant with the freedesktop standard ([link](https://www.freedesktop.org/wiki/Specifications/desktop-bookmark-spec/)). Some timestamp is not in the correct format. Also, other tests should be conducted to be sure it handle all the properties in the right way.

**Comment by francesco-gaglione** [comment]
@mmstick tested with different scenarios. Some improvements can be done on the mime detection but now this is the best solution that we have in rust. Probably in future we can consider to create a mime detection repo compliant with freedesktop, bur right now it works. I just have small doubts about why gnome files delete everything (after editing with this). I will investigate but it all seems to be in accordance with the standard. Let me know if the current behavior fits.

**Comment by francesco-gaglione** [comment]
Issue found, wrong node name but quick xml is not able to deserialize namespaces so we cannot follow the standard with the current implementation. Im considering if contribute to quick xml or create a custom parser

**Comment by francesco-gaglione** [comment]
@mmstick at the end I created a custom writer handling manually the tags name (since the namespace issue). Probably some improvements can be done, but now it is ready and compatible with freedesktop standard. Nautilus from gnome don't erase the content anymore and read the file in the right way.

**Review by mmstick — APPROVED** [review]

**Comment by mmstick** [comment]
Thanks!

**Pull request merged**
